### PR TITLE
UI Description and Screenshots added.

### PR DESCRIPTION
**Pull request by alokchoudharyguliya**
Added the description and screenshot of UI after button added into the `README.md` file

### CODE REVIEW

**Review by mahaveergurjar — APPROVED** [review]

**Comment by mahaveergurjar** [comment]
Thanks

**Comment by mahaveergurjar** [comment]
Hii @Pseudophoenix  can you add your name also like this type in readme 
image


also add dark and light theme in feature 

image

**Comment by alokchoudharyguliya** [comment]
Will do

**Comment by mahaveergurjar** [comment]
ok

**Pull request merged**
