### PR TITLE
Audio and image processing and small screen issue resolved . 

### PR DESCRIPTION
**Pull request by surajgsn07**
1. Audio and image processing integrated . 
2. Drag and drop box for input . 
3. Fixed the responsive issue in smaller screens.
Screenshot 2024-10-03 180252
Screenshot 2024-10-03 180326

### CODE REVIEW

**Comment by mahaveergurjar** [comment]
Normal text input not work without image text not accept fix this issue 


Don't not make transparent background of upload file pop 

image

**Comment by surajgsn07** [comment]
drag and drop transparent issue resolved  ✅
only text input issue resolved ✅

**Comment by mahaveergurjar** [comment]
Pdf not support only support image, audio video can you increase more  variety of file format like .pdf .doc .xls

**Comment by mahaveergurjar** [comment]
I merge your pr but make one more pr to support more file formats ok like pdf, doc, xls, html, css, js , cpp , java and etc necessary  file formats okay

**Comment by mahaveergurjar** [comment]
Thanks for your contribution in his project

**Comment by mahaveergurjar** [comment]
Thanks for your contribution in this project

**Comment by surajgsn07** [comment]
> Pdf not support only support image, audio video can you increase more variety of file format like .pdf .doc .xls

yeah sure....i will be making that pr after my hackathon on 4-5 oct.

**Comment by mahaveergurjar** [comment]
Okay no problem 👍🏻

**Pull request merged**
