### PR TITLE
Feature/theme button

### PR DESCRIPTION
**Pull request by alokchoudharyguliya**
I have made the changes in following files at  following lines:

* renderer.js -5,6,33,34,37-47
* index.html - 18,19
* styles.css - 120-131, 133-137, 258-320
Also asset folder added along.

### CODE REVIEW

**Review by mahaveergurjar — APPROVED** [review]

**Comment by mahaveergurjar** [comment]
Thanks but remember next time not push .env file in any project ok its carry important you should rename .env.example to .env so .env are added in .gitignore so not added on github

**Comment by alokchoudharyguliya** [comment]
Thankyou sir .... Will take care in future

**Comment by alokchoudharyguliya** [comment]
I had one query...will this be counted for my hacktoberfest contribution or not....and if not what had to be done for same??

**Comment by mahaveergurjar** [comment]
its counted in hacktoberfest you can see in your hacktoberfest profile

**Comment by alokchoudharyguliya** [comment]
ok just heard by that guy to attach hacktoberfest label...what is that?

**Comment by mahaveergurjar** [comment]
To track its part of hacktoberfest

**Comment by mahaveergurjar** [comment]
If you are worried about this pr are count or not then you can also make one more pr ok to update readme also add  dark and light theme screenshot and also right about in feature of dark and light mode ok @Pseudophoenix

**Comment by alokchoudharyguliya** [comment]
Sure

**Comment by mahaveergurjar** [comment]
you can make issue of readme ok i label as hacktoberfest like readme are old not added new feature like theme mode

**Pull request merged**
