### PR TITLE
added the image processing feature

### PR DESCRIPTION
**Pull request by surajgsn07**
Image input processing is added . Now user is able to send the image as well as the input as response . For example : user can get the caption for their picture and many more uses . 
Screenshot 2024-10-02 000535
Screenshot 2024-10-02 001007

### CODE REVIEW

**Comment by mahaveergurjar** [comment]
Thanks, Its also accept file so make its look like show file thumbnail and change icon camera icon into file type icon 
also not properly responsive make it responsive send icon not see clearly 
image 

I think remove the name type here then the layout not see proper issue is  fix

**Comment by mahaveergurjar** [comment]
Can you also make drag and drop type file upload ???

**Comment by surajgsn07** [comment]
> Can you also make drag and drop type file upload ???

Yeah sure....

**Comment by mahaveergurjar** [comment]
Okay

**Pull request closed without merging**
